
import uploadImage from '../lib/uploadImage.js';
const handler = async (m, {conn, text, args, usedPrefix, command}) => {

function pickRandom(list) {
return list[Math.floor(list.length * Math.random())]}
  const categories = [
        'Geral',
        'Historia',
        'Mitologia',
        'Arte',
        'Tecnologia',
        'Informatica',
        'Programacao',
        'Fisica',
        'Quimica',
        'Biologia',
        'Matematica',
        'Música',
        'Filosofia',
        'Literatura',
        'Medicina',
        'Economia',
        'Politica',
        'Astronomia',
        'Psicologia',
        'Sociologia',
        'Arqueologia',
        'Criminologia',
        'CulturaPop',
        'CulturaGotica',
        // Adicione mais categorias conforme necessário
    ];
if (!text) {
    

    const categoryList = categories.map((category, index) => `    ┃ .fatos ${index + 1} - ${category}`).join('\n');

    throw `
    ╭━━━『𝐂𝐮𝐫𝐢𝐨𝐬𝐢𝐝𝐚𝐝𝐞𝐬』━━━⬣
    ┃
${categoryList}
    ┃
    ┃┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ 
    ┃ 𝓔𝓭𝓲𝓬̧𝓪̃𝓸 𝓐𝓵𝓵𝓪𝓷 𝓑𝓸𝓽 🐈‍⬛ | ${vs}
    ╰━━━━━━━━━━━━━━━━━━⬣`;
}
else {
    const selectedCategoryIndex = parseInt(text) - 1;
    
     console.log(text)
    if (selectedCategoryIndex >= 0 && selectedCategoryIndex < categories.length) {
        
        
        
        
          const curiositiesGeral = ["Curiosidade Geral 1", "Curiosidade Geral 2"];
    const curiositiesHistoria = ["Curiosidade História 1", "Curiosidade História 2"];
    const curiositiesMitologia = ["Curiosidade Mitologia 1", "Curiosidade Mitologia 2"];
    const curiositiesArte = ["Curiosidade Arte 1", "Curiosidade Arte 2"];
    const curiositiesTecnologia = ["Curiosidade Tecnologia 1", "Curiosidade Tecnologia 2"];
    const curiositiesInformatica = ["Curiosidade Informática 1", "Curiosidade Informática 2"];
    const curiositiesProgramacao = ["Curiosidade Programação 1", "Curiosidade Programação 2"];
    const curiositiesFisica = ["Curiosidade Física 1", "Curiosidade Física 2"];
    const curiositiesQuimica = ["Curiosidade Química 1", "Curiosidade Química 2"];
    const curiositiesBiologia = ["Curiosidade Biologia 1", "Curiosidade Biologia 2"];
    const curiositiesMatematica = ["Curiosidade Matemática 1", "Curiosidade Matemática 2"];
    const curiositiesMusica = ["Curiosidade Música 1", "Curiosidade Música 2"];
    const curiositiesFilosofia = ["Curiosidade Filosofia 1", "Curiosidade Filosofia 2"];
    const curiositiesLiteratura = ["Curiosidade Literatura 1", "Curiosidade Literatura 2"];
    const curiositiesMedicina = [
      "A penicilina, o primeiro antibiótico descoberto, foi isolada por Alexander Fleming em 1928 a partir do fungo Penicillium.",
  "A vacinação, introduzida por Edward Jenner no século XVIII, é uma das maiores conquistas da medicina para prevenção de doenças infecciosas.",
  "A cirurgia laparoscópica revolucionou procedimentos cirúrgicos ao usar pequenas incisões e uma câmera para visualizar o interior do corpo.",
  "A teoria germinal das doenças, desenvolvida por Louis Pasteur e outros, fundamentou a compreensão moderna das infecções.",
  "A terapia genética, uma área emergente, visa corrigir ou substituir genes defeituosos para tratar doenças genéticas.",
  "A ressonância magnética (RM) é uma técnica avançada de imagem médica que usa campos magnéticos e ondas de rádio para visualizar órgãos internos.",
  "A aspirina, derivada do salicilato de salgueiro, é usada como analgésico, anti-inflamatório e anticoagulante.",
  "A anestesia geral, desenvolvida no século XIX, permitiu cirurgias sem dor, melhorando significativamente os procedimentos médicos.",
  "A endoscopia é uma técnica que utiliza um tubo flexível com uma câmera para examinar o interior do trato digestivo e outros órgãos.",
  "A teoria celular, formulada no século XIX, postula que todos os organismos são compostos por células, sendo a base da biologia moderna.",
  "A terapia hormonal, usada em certos cânceres, regula o crescimento celular ao interferir nas vias hormonais.",
  "O transplante de órgãos, como rim e coração, tem salvado vidas, mas enfrenta desafios como a escassez de doadores.",
  "A imunoterapia, uma abordagem inovadora, utiliza o sistema imunológico para combater cânceres e outras doenças.",
  "O genoma humano foi sequenciado no Projeto Genoma Humano, abrindo caminho para a compreensão das bases genéticas de doenças.",
  "A descoberta dos raios X por Wilhelm Roentgen em 1895 revolucionou o diagnóstico médico ao permitir visualização interna sem invasões.",
  "A quimioterapia, desenvolvida a partir de agentes químicos, é uma abordagem comum no tratamento do câncer.",
  "A anestesia local, introduzida no século XIX, permite a insensibilidade em áreas específicas durante procedimentos cirúrgicos.",
  "A teoria dos germes levou à adoção de práticas de higiene, reduzindo significativamente a propagação de doenças infecciosas.",
  "A tomografia computadorizada (TC) combina raios X e computadores para criar imagens detalhadas de estruturas internas.",
  "A terapia antirretroviral (TAR) transformou o tratamento do HIV, convertendo a infecção em uma condição gerenciável.",
  "A técnica de clonagem, embora controversa, abriu caminho para avanços em pesquisa e medicina regenerativa.",
  "A vacina contra a poliomielite, desenvolvida por Jonas Salk e Albert Sabin, levou à quase erradicação da doença.",
  "A radioterapia utiliza radiação para tratar cânceres, visando destruir células cancerígenas ou impedir seu crescimento.",
  "A eletroconvulsoterapia (ECT) é usada em certos transtornos psiquiátricos, embora seu mecanismo exato não seja totalmente compreendido.",
  "O sequenciamento de nova geração (NGS) revolucionou a genômica, permitindo análises rápidas e abrangentes do DNA.",
  "O código de ética de Hipócrates, estabelecido há milênios, ainda influencia princípios éticos na prática médica.",
  "A cirurgia robótica, utilizando robôs controlados por cirurgiões, oferece precisão e menos invasão em procedimentos complexos.",
  "A terapia gênica ex vivo envolve modificar células fora do corpo antes de reintroduzi-las para tratar condições genéticas.",
  "A pílula anticoncepcional, introduzida nos anos 1960, trouxe uma revolução na contracepção e controle de natalidade.",
  "A hipótese microbiana das doenças, desenvolvida por Louis Pasteur e Robert Koch, estabeleceu a ligação entre microrganismos e infecções.",
  "A terapia cognitivo-comportamental (TCC) é uma abordagem eficaz para transtornos mentais, focando em padrões de pensamento e comportamento.",
  "A aspiração a vácuo, desenvolvida na década de 1960, é um método seguro e comum para interrupção da gravidez no primeiro trimestre.",
  "O Prêmio Nobel de Medicina foi concedido a cientistas como Marie Curie, por suas contribuições para a radioterapia, e James Watson e Francis Crick, pela estrutura do DNA.",
  "A teoria do controle de natalidade hormonal foi proposta por Gregory Pincus e John Rock, levando ao desenvolvimento da pílula anticoncepcional.",
  "A terapia de reposição hormonal (TRH) é usada para aliviar sintomas da menopausa, mas apresenta riscos associados.",
  "A medicina regenerativa explora métodos para reparar ou substituir tecidos danificados ou órgãos.",
  "O sistema de classificação de doenças (CID) é usado internacionalmente para categorizar condições médicas.",
  "A eutanásia, o ato de induzir a morte para aliviar o sofrimento, é um tema ético e legalmente complexo.",
  "A primeira anestesia geral em cirurgia foi administrada por William Morton em 1846, marcando um avanço significativo.",
  "A cirurgia plástica reconstrutiva visa restaurar a função e a aparência após lesões ou defeitos congênitos.",
    "A terapia fotodinâmica é um tratamento que utiliza luz e um agente fotossensível para destruir células cancerígenas.",
  "A ressonância magnética funcional (fMRI) é uma técnica que mapeia a atividade cerebral ao medir as mudanças no fluxo sanguíneo.",
  "O conceito de telecirurgia envolve cirurgiões realizando procedimentos remotamente, controlando robôs cirúrgicos.",
  "Os nanorrobôs médicos são dispositivos em escala nanométrica projetados para realizar tarefas específicas dentro do corpo humano.",
  "A estimulação cerebral profunda (DBS) utiliza eletrodos implantados para tratar condições neurológicas, como o Mal de Parkinson.",
  "A impressão 3D tem sido usada para criar órgãos artificiais, como rins, para eventual transplante.",
  "A telemedicina não se limita apenas a consultas virtuais; abrange diagnósticos remotos e monitoramento de pacientes.",
  "A genômica personalizada visa adaptar tratamentos com base no perfil genético único de cada paciente.",
  "O microbioma humano, composto por trilhões de microorganismos, desempenha um papel crucial na saúde e na doença.",
  "A terapia gênica ex vivo envolve modificar células fora do corpo antes de reintroduzi-las para tratar condições genéticas.",
  "A farmacogenômica personaliza tratamentos com base na genética do paciente, otimizando a eficácia e reduzindo efeitos adversos.",
   "A terapia EMDR (Desensibilização e Reprocessamento por Movimentos Oculares) é utilizada para tratar transtornos de estresse pós-traumático.",
  "A hipnose terapêutica é aplicada para ajudar em questões como controle da dor, fobias e transtornos alimentares.",
  "A terapia com realidade virtual é empregada no tratamento de transtornos de ansiedade, fobias e PTSD, oferecendo ambientes simulados para exposição controlada.",
  "A terapia de exposição é uma abordagem comportamental que ajuda os pacientes a enfrentarem gradualmente situações temidas para superar ansiedades e medos.",
  "A psicoterapia psicodinâmica explora padrões inconscientes de pensamento e comportamento para entender questões emocionais e promover a mudança.",
  "A terapia de reposição hormonal (TRH) é usada para aliviar sintomas da menopausa, como ondas de calor e alterações de humor.",
  "A quiropraxia é uma prática alternativa que se concentra na manipulação da coluna vertebral para melhorar a saúde geral e aliviar dores.",
  "A terapia cognitivo-comportamental (TCC) online, realizada remotamente, tem se mostrado eficaz no tratamento de vários transtornos mentais.",
  "A terapia de biofeedback ensina os pacientes a controlarem funções corporais como frequência cardíaca e pressão arterial para melhorar a saúde mental.",
  "A terapia de reminiscência é frequentemente utilizada para idosos, envolvendo a discussão de eventos passados para promover o bem-estar emocional.",
  "A cirurgia refrativa a laser, como o LASIK, remodela a córnea para corrigir problemas de visão, eliminando a necessidade de óculos ou lentes de contato.",
  "A terapia de estimulação magnética transcraniana (TMS) é uma opção para tratar depressão resistente, aplicando campos magnéticos para estimular áreas do cérebro.",
  "A medicina regenerativa tem explorado o uso de células-tronco para reparar tecidos danificados, oferecendo novas perspectivas para lesões e doenças crônicas.",
  "A terapia com luz azul é utilizada para tratar transtorno afetivo sazonal (TAS), proporcionando exposição à luz para aliviar sintomas de depressão sazonal.",
  "A terapia de exposição virtual é usada no tratamento de fobias, permitindo que os pacientes enfrentem virtualmente seus medos em um ambiente controlado.",
  "A cirurgia bariátrica não é apenas para perda de peso; também demonstrou melhorar condições como diabetes tipo 2 e apneia do sono.",
  "A terapia de relaxamento progressivo envolve a tensão e o relaxamento de grupos musculares específicos para aliviar o estresse e promover a calma.",
  "A terapia assistida por animais utiliza a interação com animais para melhorar aspectos físicos, sociais, emocionais e cognitivos da vida dos pacientes.",
  "A terapia focalizada na compaixão é uma abordagem terapêutica que visa desenvolver habilidades de auto-compaixão e reduzir a autocrítica.",
  "A terapia de liberação miofascial trata pontos de dor e rigidez no tecido conjuntivo, promovendo a liberação de restrições musculares.",
  "A terapia de realidade aumentada tem sido explorada como ferramenta de reabilitação, criando ambientes virtuais para melhorar a motivação e o engajamento dos pacientes.",
  "A terapia de grupo pode ser eficaz para diversos transtornos, proporcionando apoio social e insights de diferentes perspectivas.",
  "A terapia de ressonância magnética focalizada guiada por ultrassom (MRgFUS) é uma opção não invasiva para tratar tumores, utilizando feixes de ultrassom focalizados.",
  "A terapia com neurofeedback visa melhorar a autorregulação cerebral, ajudando pacientes a controlarem atividades cerebrais associadas a diferentes estados mentais.",
  "A terapia gênica tem o potencial de corrigir defeitos genéticos, oferecendo promissoras opções de tratamento para condições genéticas raras."
  ];
    const curiositiesPolitica = [
      
       "O Brasil é uma república federativa, composta por 26 estados e um Distrito Federal.",
  "Portugal foi a primeira nação europeia a abolir a pena de morte, em 1867.",
  "O sistema político do Brasil é uma democracia representativa, onde os cidadãos elegem representantes para tomarem decisões em seu nome.",
  "O Tratado de Lisboa, assinado em 2007, reformou o funcionamento da União Europeia (UE) e seus processos de decisão.",
  "A Constituição de 1988 é a atual Constituição do Brasil, consolidando princípios democráticos e direitos fundamentais.",
  "O Reino Unido adotou o sistema de voto alternativo nas eleições para o Parlamento Europeu em 1999.",
  "O Brasil é uma república presidencialista, onde o presidente exerce tanto funções de chefe de Estado quanto de chefe de governo.",
  "O Acordo de Schengen, assinado em 1985, permite a livre circulação de pessoas entre países europeus signatários, eliminando controles fronteiriços.",
  "A Itália foi uma das fundadoras da Comunidade Europeia em 1957, juntamente com França, Alemanha, Bélgica, Luxemburgo e Países Baixos.",
  "O Brasil tem um sistema bicameral, com uma Câmara dos Deputados e um Senado Federal.",
  "A Revolução dos Cravos em Portugal, em 1974, pôs fim à ditadura e estabeleceu um governo democrático.",
  "O Tratado de Lisboa também estabeleceu a Carta dos Direitos Fundamentais da União Europeia.",
  "O Brasil é o maior país da América do Sul em extensão territorial e população.",
  "A Alemanha é conhecida por seu sistema federativo, com 16 estados (Länder), cada um com seu próprio governo e parlamento.",
  "O voto é obrigatório no Brasil para cidadãos entre 18 e 70 anos; para jovens de 16 e 17 anos e idosos entre 70 e 79 anos, o voto é facultativo.",
  "O Acordo de Schengen inclui atualmente 27 países, a maioria dos quais faz parte da União Europeia.",
  "A Suíça é um país europeu que não faz parte da União Europeia, mas faz parte do Espaço Schengen.",
  "O Brasil adotou o sistema de voto eletrônico nas eleições em 1996, sendo um dos pioneiros nessa tecnologia.",
  "A criação da Comunidade Econômica Europeia (CEE) em 1957 foi um dos passos iniciais para a formação da União Europeia.",
  "O presidente da República do Brasil é eleito por voto direto para um mandato de quatro anos, podendo ser reeleito por mais um mandato consecutivo.",
  "O Reino Unido optou por deixar a União Europeia no referendo de 2016, um processo conhecido como Brexit.",
  "O Brasil foi colonizado pelos portugueses em 1500, e a independência foi declarada em 1822.",
  "A França adotou o sufrágio feminino em 1944, tornando-se uma das primeiras nações europeias a fazê-lo.",
  "A UE tem três instituições principais: o Parlamento Europeu, o Conselho da União Europeia e a Comissão Europeia.",
  "A Holanda é uma monarquia constitucional, onde o rei é o chefe de Estado, mas suas funções são em grande parte cerimoniais.",
  "O Brasil foi governado por um regime militar entre 1964 e 1985, período conhecido como Ditadura Militar.",
  "A Comissão Europeia é responsável por propor legislação e garantir a implementação das decisões na União Europeia.",
  "O sistema político da Alemanha é uma república parlamentar, onde o presidente é o chefe de Estado e o chanceler é o chefe de governo.",
  "O Brasil foi o último país das Américas a abolir a escravidão em 1888.",
  "A Bulgária aderiu à União Europeia em 2007, tornando-se o membro de número 27.",
  "A UE tem uma moeda comum, o euro, que é usada por 19 dos 27 estados membros.",
  "A Suécia tem uma política externa de não participação em alianças militares, embora seja membro da União Europeia.",
  "O Brasil tem uma política externa de não intervenção, não interferência e defesa da autodeterminação dos povos.",
  "O conceito de cidadania europeia foi introduzido pelo Tratado de Maastricht em 1992, conferindo direitos aos cidadãos dos estados membros.",
  "O sistema eleitoral da Alemanha é misto, combinando votos proporcionais e majoritários.",
  "A Áustria é um dos seis países fundadores da União Europeia, assinando o Tratado de Roma em 1957.",
  "O Brasil é um dos maiores produtores mundiais de alimentos, exportando produtos como soja, carne e café.",
  "A União Europeia tem políticas de coesão para reduzir as disparidades econômicas entre suas regiões.",
  "O sistema político da França é uma república semipresidencialista, com um presidente e um primeiro-ministro.",
  "O sistema eleitoral português usa o método de representação proporcional para eleições parlamentares.",
  "O Brasil tem uma das maiores reservas de água doce do mundo, com a Amazônia representando grande parte desse recurso.",
  "O presidente da França é eleito por sufrágio direto para um mandato de cinco anos.",
  "A União Europeia possui uma política externa e de segurança comum, buscando uma abordagem coordenada em questões internacionais.",
  "A lei eleitoral na Alemanha permite que os eleitores votem tanto no partido quanto em candidatos individuais.",
  "O sistema político da Itália é uma república parlamentar, com um presidente como chefe de Estado e um primeiro-ministro como chefe de governo."];
    const curiositiesEconomia = [
      "O Brasil é uma das maiores economias do mundo, sendo classificado como uma economia de mercado emergente.",
  "A Zona Euro é uma área monetária composta por 19 dos 27 estados membros da União Europeia que adotaram o euro como moeda.",
  "O Índice de Desenvolvimento Humano (IDH) é uma medida composta que avalia o bem-estar humano com base em indicadores como expectativa de vida, educação e renda.",
  "A crise financeira global de 2008 teve impactos significativos na economia mundial, resultando em recessões e instabilidade nos mercados financeiros.",
  "O Produto Interno Bruto (PIB) é uma medida do valor total de bens e serviços produzidos por um país em um determinado período.",
  "A Bolsa de Valores de São Paulo (B3) é a principal bolsa de valores do Brasil, onde as ações de empresas são negociadas.",
  "A austeridade fiscal é uma política que visa reduzir os déficits fiscais por meio de cortes de gastos e aumento de impostos.",
  "A União Europeia é um bloco econômico que visa a integração econômica e política entre os países membros.",
  "O índice Dow Jones Industrial Average é um dos indicadores mais conhecidos do desempenho do mercado de ações nos Estados Unidos.",
  "O conceito de inflação refere-se ao aumento geral contínuo dos preços dos bens e serviços em uma economia.",
  "A criação do euro, moeda única da Zona Euro, entrou em circulação em notas e moedas em 2002.",
  "O Brasil é um grande exportador de commodities, incluindo soja, minério de ferro, carne e açúcar.",
  "O Banco Central Europeu (BCE) é responsável pela política monetária da Zona Euro, incluindo a definição das taxas de juros.",
  "A recessão é um período de declínio econômico, muitas vezes medido por dois trimestres consecutivos de contração do PIB.",
  "O Índice de Preços ao Consumidor (IPC) é uma medida que avalia a variação de preços de um conjunto de bens e serviços consumidos pelas famílias.",
  "O Brasil é um dos maiores produtores e exportadores de carne bovina do mundo.",
  "O Plano Real, implementado no Brasil em 1994, estabilizou a moeda e controlou a inflação, promovendo estabilidade econômica.",
  "O Desenvolvimento Sustentável visa equilibrar o crescimento econômico com a preservação ambiental e justiça social.",
  "O Índice de Liberdade Econômica avalia o grau de liberdade econômica em países, levando em consideração fatores como propriedade privada e liberdade de comércio.",
  "A dívida pública é o montante que um governo deve a credores, geralmente expresso como uma porcentagem do PIB.",
  "O Brasil é um dos maiores produtores de café do mundo, sendo conhecido por sua produção de café arábica e robusta.",
  "O conceito de PIB per capita é uma medida que divide o PIB de um país pelo número de habitantes, fornecendo uma indicação média de renda.",
  "O Fundo Monetário Internacional (FMI) é uma organização internacional que oferece assistência financeira e aconselhamento econômico a seus países membros.",
  "O Produto Interno Bruto (PIB) nominal reflete o valor total dos bens e serviços a preços de mercado correntes, sem ajuste para inflação.",
  "A globalização é um fenômeno que envolve a interconexão econômica, cultural e política entre diferentes partes do mundo.",
  "O Brasil é um dos principais produtores mundiais de biocombustíveis, como etanol derivado da cana-de-açúcar.",
  "O Tratado de Lisboa, assinado em 2007, visa melhorar a eficiência e a transparência das instituições da União Europeia.",
  "O conceito de mão invisível, proposto por Adam Smith, sugere que as interações do mercado levam a resultados benéficos para a sociedade.",
  "O Brasil é um dos BRICS, grupo formado por Brasil, Rússia, Índia, China e África do Sul, que busca cooperação econômica.",
  "A moeda brasileira, o real, foi introduzida em 1994, substituindo o cruzeiro real como parte do Plano Real.",
  "O mercado de ações é um sistema onde os investidores compram e vendem títulos, como ações de empresas, buscando lucro.",
  "A taxa básica de juros, conhecida como Selic no Brasil, influencia o custo do crédito, a inflação e o desempenho econômico geral.",
  "O Brasil é um dos maiores produtores e exportadores de soja do mundo, desempenhando um papel crucial na agricultura global.",
  "A privatização é o processo de transferir a propriedade e gestão de empresas estatais para o setor privado.",
  "O Banco Central do Brasil é responsável pela implementação da política monetária e pela emissão de moeda no país.",
  "A Zona de Livre Comércio da Associação Europeia de Livre Comércio (EFTA) inclui países como Noruega, Islândia, Suíça e Liechtenstein.",
  "O Brasil é um dos maiores produtores mundiais de minério de ferro, sendo uma commodity crucial para a indústria siderúrgica.",
  "A Lei de Responsabilidade Fiscal, implementada no Brasil em 2000, estabelece regras para o gasto público, visando a responsabilidade fiscal.",
  "O Banco Central Europeu (BCE) tem o mandato de manter a estabilidade de preços na Zona Euro, com uma meta de inflação.",
  "O conceito de 'déficit orçamentário ocorre quando os gastos de um governo excedem suas receitas em um determinado período.",
  "O Brasil é um importante produtor de biocombustíveis, sendo o etanol derivado da cana-de-açúcar uma fonte significativa de energia renovável."
      ];
    const curiositiesAstronomia = [
      "A Via Láctea, nossa galáxia, contém bilhões de estrelas, planetas e outros corpos celestes.",
  "O Sol representa mais de 99% da massa do sistema solar e desempenha um papel fundamental na sustentação da vida na Terra.",
  "Um ano em Marte é quase o dobro do comprimento de um ano na Terra, pois Marte leva aproximadamente 687 dias para orbitar o Sol.",
  "Júpiter, o maior planeta do sistema solar, possui uma grande mancha vermelha que é uma tempestade antiga e maciça.",
  "A lua Europa de Júpiter tem uma crosta de gelo que os cientistas acreditam que esconde um oceano líquido abaixo da superfície.",
  "Astrônomos usam o termo 'anos-luz' para medir distâncias em termos do tempo que a luz leva para percorrer essas distâncias.",
  "Uma estrela de nêutrons é o núcleo colapsado de uma estrela maciça que explodiu em uma supernova, sendo incrivelmente densa.",
  "A luz das estrelas que vemos à noite pode ter viajado por milhões de anos antes de chegar à Terra.",
  "A gravidade em um buraco negro é tão intensa que nada, nem mesmo a luz, pode escapar dele, criando uma região chamada horizonte de eventos.",
  "A expansão do universo está acontecendo, o que significa que as galáxias estão se afastando umas das outras ao longo do tempo.",
  "Estrelas de nêutrons podem girar extremamente rápido e são conhecidas como pulsares quando emitem pulsos regulares de radiação.",
  "Buracos negros supermassivos residem nos centros de muitas galáxias, incluindo a Via Láctea.",
  "A aurora boreal ocorre quando partículas carregadas do Sol interagem com a magnetosfera da Terra, criando belas luzes no céu.",
  "As luas de Saturno, como Titã e Encélado, têm características únicas, incluindo lagos de metano e plumas de gelo.",
  "Quasares são núcleos galácticos ativos com emissões extremamente intensas e são alguns dos objetos mais brilhantes do universo.",
  "A maior montanha conhecida em nosso sistema solar está em Marte - o Monte Olimpo, que é quase três vezes mais alto que o Monte Everest.",
  "O universo observável contém bilhões de galáxias, cada uma composta por bilhões ou trilhões de estrelas.",
  "O Telescópio Espacial Hubble tem proporcionado incríveis imagens do universo e contribuiu significativamente para nossa compreensão cósmica.",
  "A matéria escura, embora invisível, constitui a maior parte da massa do universo e exerce uma influência gravitacional significativa.",
  "Um ano em Plutão dura mais de 248 anos terrestres, e Plutão já foi classificado como o nono planeta do sistema solar.",
  "A lua Io de Júpiter é o objeto mais vulcânico conhecido, com erupções de enxofre visíveis a partir da Terra.",
  "Os cometas, com suas longas caudas, são compostos principalmente de gelo, poeira e partículas rochosas.",
  "A colisão de asteroides ou cometas com a Terra é uma ameaça potencial, e os cientistas estudam métodos para prevenir impactos catastróficos.",
  "A teoria do Big Bang é a explicação científica dominante para a origem do universo, sugerindo uma expansão a partir de um estado inicial quente e denso.",
  "O telescópio espacial James Webb, programado para lançamento, será um dos observatórios mais poderosos já enviados ao espaço.",
  "Os quatro maiores planetas do sistema solar - Júpiter, Saturno, Urano e Netuno - são conhecidos como gigantes gasosos.",
  "As estrelas passam por um ciclo de vida que inclui estágios como a nebulosa, estrela de sequência principal, gigante vermelha e anã branca.",
  "O cinturão de Kuiper é uma região além da órbita de Netuno que contém muitos objetos pequenos, incluindo Plutão e outros planetas anões.",
  "Os raios gama são a forma mais energética de radiação e são produzidos em eventos cósmicos como supernovas e buracos negros.",
  "O som não pode se propagar no vácuo do espaço, tornando-o silencioso mesmo que existam eventos cósmicos incrivelmente poderosos.",
  "Os telescópios de rádio são usados para observar emissões de rádio do espaço, permitindo a detecção de objetos invisíveis em luz visível.",
  "As manchas solares são regiões mais frias na superfície do Sol, associadas a campos magnéticos intensos.",
  "A constante cosmológica, proposta por Einstein, é uma energia escura que impulsiona a expansão do universo.",
  "A sonda Voyager 1 é a espaçonave mais distante da Terra e entrou no espaço interestelar, carregando uma mensagem para possíveis civilizações extraterrestres.",
  "A colisão entre galáxias é um fenômeno cósmico comum, resultando em interações gravitacionais dramáticas.",
  "A estrela mais próxima da Terra, além do Sol, é Proxima Centauri, uma anã vermelha localizada no sistema Alpha Centauri.",
  "Os buracos de minhoca são hipotéticas pontes no espaço-tempo que podem conectar diferentes partes do universo.",
  "A Terra não é uma esfera perfeita, mas sim um esferoide oblato devido à rotação, resultando em um leve achatamento nos polos.",
  "A detecção de ondas gravitacionais em 2015 confirmou uma das previsões da teoria da relatividade de Einstein.",
  "O campo magnético da Terra protege contra a radiação solar, desviando partículas carregadas ao redor do planeta.",
  "A Estação Espacial Internacional (ISS) orbita a Terra e serve como um laboratório para pesquisa em ambiente de microgravidade",
   "Estrelas de nêutrons, formadas a partir de colapsos de supernovas, são incrivelmente densas, com a massa do Sol comprimida em um diâmetro de aproximadamente 20 quilômetros.",
  "A teoria da relatividade temporal, proposta por Einstein, sugere que o tempo é relativo e pode ser influenciado pela gravidade e velocidade.",
  "Ponte de Einstein-Rosen, também conhecida como buraco de minhoca, é uma solução teórica das equações de campo de Einstein que sugere a existência de túneis no espaço-tempo, potencialmente conectando diferentes regiões do universo.",
  "A teoria M é uma teoria unificada que busca unificar todas as teorias de cordas possíveis, permitindo diferentes dimensões espaciais e temporal.",
  "A teoria de p-branas, uma extensão da teoria das cordas, sugere que o universo pode ter dimensões extras além das três espaciais e uma temporal.",
  "A fusão de estrelas de nêutrons pode resultar na formação de buracos negros e é acompanhada por eventos cósmicos chamados de ondas gravitacionais.",
  "A dilatação temporal, prevista pela relatividade, significa que o tempo passa mais devagar em regiões de maior gravidade, como perto de um buraco negro.",
  "Os pulsares, estrelas de nêutrons que emitem feixes de radiação em direções específicas, são usados como relógios cósmicos de alta precisão.",
  "A ponte de Einstein-Rosen, se existisse, poderia potencialmente permitir viagens entre diferentes regiões do espaço-tempo, embora ainda seja uma especulação teórica.",
  "A teoria M sugere que diferentes universos podem coexistir em uma estrutura mais ampla, conhecida como 'braneworld' ou 'mundo das branas'.",
  "A teoria de p-branas propõe que as partículas fundamentais podem ser representadas como membranas vibrantes, em vez de pontos.",
  "As ondas gravitacionais, previstas por Einstein, foram detectadas pela primeira vez em 2015, proporcionando uma nova maneira de estudar eventos cósmicos massivos.",
  "A teoria M incorpora diferentes versões da teoria das cordas, permitindo uma compreensão mais abrangente dos fenômenos físicos no universo.",
  "A teoria de p-branas, ao incorporar dimensões adicionais, oferece uma perspectiva interessante sobre a natureza fundamental das partículas subatômicas.",
  "A radiação de Hawking, proposta por Stephen Hawking, sugere que buracos negros podem emitir radiação devido a processos quânticos próximos ao horizonte de eventos.",
  "A teoria das cordas, parte integrante da teoria M, propõe que as partículas fundamentais não são pontos, mas sim cordas vibrantes.",
  "A teoria das cordas requer a existência de múltiplas dimensões espaciais para ser matematicamente consistente.",
  "A energia escura, responsável pela aceleração da expansão do universo, é um dos maiores mistérios em astronomia e física teórica.",
  "Os buracos negros são objetos cósmicos cuja gravidade é tão intensa que nada, nem mesmo a luz, pode escapar de sua atração.",
  "A teoria das cordas aborda questões fundamentais da física, como a unificação das forças fundamentais e a natureza das partículas subatômicas.",
  "A expansão acelerada do universo, observada em experimentos, é atribuída à energia escura.",
  "A teoria das cordas propõe que as partículas subatômicas são manifestações diferentes das vibrações fundamentais das cordas.",
  "A relatividade geral, formulada por Einstein, descreve a gravidade como a curvatura do espaço-tempo devido à presença de massa e energia.",
  "A sonda Voyager 1, ao entrar no espaço interestelar, fornece dados importantes sobre as condições além da influência direta do Sol.",
  "A teoria M sugere que o universo pode ter mais dimensões além das três espaciais e uma temporal, algumas delas podem ser compactificadas e imperceptíveis.",
  "Os quasares, além de serem objetos extremamente brilhantes, são cruciais para o estudo de condições no universo primitivo.",
  "A teoria das cordas tem várias versões, incluindo a teoria tipo I, a teoria tipo IIA e a teoria tipo IIB.",
  "A radiação cósmica de fundo, remanescente do Big Bang, é uma das evidências mais importantes que apoiam a teoria do Big Bang.",
  "A teoria de p-branas sugere que as dimensões adicionais podem ser compactificadas em tamanhos muito pequenos, explicando por que não as percebemos diretamente.",
  "A expansão do universo implica que a luz de objetos distantes sofre um desvio para o vermelho devido à expansão do espaço entre nós e esses objetos.",
  "A teoria das cordas propõe a existência de partículas supersimétricas, que poderiam ajudar a resolver problemas não resolvidos pela física de partículas tradicional.",
  "A detecção de exoplanetas, planetas fora do nosso sistema solar, contribui significativamente para a compreensão da formação e distribuição de planetas no universo.",
  "A teoria das cordas, se confirmada, terá implicações profundas para a compreensão da natureza fundamental da realidade e da matéria.",
  "A teoria M busca unificar as diferentes teorias de cordas em uma estrutura coesa, proporcionando uma descrição mais abrangente do universo.",
  "A radiação de Hawking, prevista para buracos negros, é um exemplo de fenômenos quânticos influenciando condições extremas no cosmos.",
  "A teoria das cordas propõe que as cordas podem vibrar em diferentes modos, dando origem às partículas elementares observadas na natureza."
      ];
    const curiositiesPsicologia = [
      "A psicologia é a ciência que estuda o comportamento humano e os processos mentais.",
  "Sigmund Freud é considerado o pai da psicanálise, uma abordagem que destaca a importância do inconsciente.",
  "A teoria behaviorista, associada a B.F. Skinner, enfatiza a observação do comportamento e suas consequências.",
  "A psicologia humanista, com Carl Rogers e Abraham Maslow, destaca o crescimento pessoal e a realização do potencial humano.",
  "A teoria cognitiva, de Jean Piaget, explora como as pessoas processam informações, aprendem e resolvem problemas.",
  "A psicologia evolucionista investiga como os processos mentais evoluíram para fornecer vantagens adaptativas.",
  "A abordagem gestalt destaca a importância de perceber objetos e situações como totalidades integradas, não apenas somas de partes.",
  "A psicologia positiva concentra-se no estudo do bem-estar, felicidade e forças humanas positivas.",
  "A teoria do apego, desenvolvida por John Bowlby, explora os laços emocionais entre crianças e seus cuidadores.",
  "A psicologia social examina como pensamentos, sentimentos e comportamentos são influenciados pelo ambiente social.",
  "O efeito placebo é um fenômeno psicológico em que uma substância inativa produz efeitos percebidos de melhora devido às expectativas.",
  "A teoria das inteligências múltiplas, de Howard Gardner, sugere que existem diferentes formas de inteligência, não apenas uma.",
  "A síndrome de Estocolmo é um fenômeno psicológico em que uma pessoa se identifica com seu captor durante um sequestro.",
  "A memória eidética, ou memória fotográfica, é a capacidade rara de lembrar imagens com detalhes precisos após uma única exposição.",
  "O teste de Rorschach, ou teste do borrão de tinta, é uma técnica projetiva usada para avaliar a personalidade e emoções.",
  "O efeito Zeigarnik destaca a tendência de as pessoas lembrarem melhor as tarefas incompletas do que as concluídas.",
  "A psicologia do desenvolvimento estuda as mudanças físicas, sociais e cognitivas ao longo da vida.",
  "O transtorno de estresse pós-traumático (TEPT) pode ocorrer após eventos traumáticos e resulta em flashbacks e ansiedade intensa.",
  "A teoria da dissonância cognitiva, de Leon Festinger, explora a tensão interna causada por crenças conflitantes.",
  "A psicologia escolar se concentra na avaliação e intervenção para apoiar o desenvolvimento acadêmico e emocional das crianças.",
  "O transtorno obsessivo-compulsivo (TOC) é caracterizado por pensamentos intrusivos e comportamentos repetitivos para reduzir a ansiedade.",
  "A psicologia do esporte estuda os fatores psicológicos que influenciam o desempenho atlético e o envolvimento esportivo.",
  "A psicologia forense aplica princípios psicológicos para entender comportamentos criminosos e contribuir para investigações judiciais.",
  "O transtorno bipolar é marcado por oscilações extremas de humor, incluindo episódios maníacos e depressivos.",
  "A psicologia da personalidade explora padrões duradouros de pensamentos, sentimentos e comportamentos de uma pessoa.",
  "A psicologia ambiental investiga como o ambiente físico influencia o bem-estar e o comportamento humano.",
  "A esquizofrenia é um transtorno mental grave caracterizado por distorções na percepção da realidade e pensamento desorganizado.",
  "A psicologia organizacional se concentra no estudo do comportamento humano nas organizações, incluindo liderança e motivação.",
  "O transtorno do espectro autista (TEA) afeta o desenvolvimento social e de comunicação, com variação na gravidade dos sintomas.",
  "A amnésia dissociativa é um distúrbio em que a pessoa experimenta perda de memória, muitas vezes associada a trauma ou estresse.",
  "A psicologia da saúde examina como fatores psicológicos influenciam a saúde física e o tratamento de doenças.",
  "O transtorno de personalidade borderline (TPB) envolve instabilidade emocional, relacionamentos tumultuados e autoimagem instável.",
  "A psicologia da publicidade estuda como as mensagens publicitárias influenciam as percepções e escolhas do consumidor.",
  "A terapia cognitivo-comportamental (TCC) é uma abordagem eficaz que visa modificar padrões de pensamento negativo e comportamentos disfuncionais.",
  "A psicologia do trânsito examina fatores psicológicos relacionados à segurança e comportamento no tráfego.",
  "A síndrome de Down é uma condição genética que resulta em características físicas distintas e atrasos no desenvolvimento cognitivo.",
  "A psicologia do consumidor estuda os processos mentais que influenciam as decisões de compra e preferências do consumidor.",
  "A terapia de exposição é comumente usada para tratar fobias, envolvendo a exposição gradual ao objeto ou situação temida.",
  "A psicologia educacional examina como os princípios psicológicos podem informar práticas de ensino e aprendizagem.",
  "O transtorno de ansiedade generalizada (TAG) envolve preocupação persistente e excessiva, muitas vezes sem motivo aparente.",
  "A psicologia do envelhecimento estuda os processos de envelhecimento cognitivo e emocional.",
  "A terapia de grupo oferece suporte psicológico em um ambiente grupal, facilitando a partilha de experiências e estratégias de enfrentamento.",
  "A psicologia criminal investiga fatores psicológicos envolvidos em comportamentos criminosos e na justiça criminal.",
  "A teoria da personalidade de Freud inclui a divisão da mente em id, ego e superego, influenciando os impulsos e comportamentos humanos.",
      ];
    const curiositiesSociologia = [
      "A teoria do construtivismo social destaca como a realidade social é construída através da interação e interpretação coletiva.",
  "A sociologia do envelhecimento examina questões relacionadas ao envelhecimento da população, cuidados aos idosos e estereótipos associados à velhice.",
  "A teoria da socialização explora como os indivíduos aprendem normas e valores sociais ao longo de suas vidas.",
  "A sociologia da religião estuda as interações entre as crenças religiosas e as estruturas sociais.",
  "A teoria do feminismo marxista destaca as interseções entre gênero, classe e raça na análise da opressão.",
  "A sociologia da cidade analisa o desenvolvimento urbano, comunidades urbanas e impactos sociais da vida na cidade.",
  "A teoria da modernização propõe que as sociedades passam por estágios previsíveis de desenvolvimento em direção à modernidade.",
  "A sociologia do trabalho explora as relações entre trabalho, emprego e estrutura social.",
  "A teoria do conflito de gênero destaca as desigualdades sociais baseadas no gênero e os sistemas patriarcais.",
  "A sociologia do conhecimento investiga como as condições sociais influenciam a produção e disseminação do conhecimento.",
  "A teoria da aculturação analisa o processo pelo qual grupos culturais diferentes entram em contato e suas culturas se modificam.",
  "A sociologia da música explora como a música reflete e molda a sociedade, identidade cultural e movimentos sociais.",
  "A teoria da modernidade tardia, também conhecida como pós-modernidade, destaca a complexidade e fragmentação nas sociedades contemporâneas.",
  "A sociologia da arte investiga como a produção artística e as instituições artísticas são influenciadas pelo contexto social.",
  "A teoria da mudança social propõe modelos explicativos para entender como e por que as sociedades mudam ao longo do tempo.",
  "A sociologia do esporte estuda as relações entre esporte, sociedade, cultura e identidade.",
  "A teoria da escolha racional na sociologia econômica destaca como os indivíduos tomam decisões baseadas em maximizar seus interesses.",
  "A sociologia da moda analisa como as tendências e práticas de moda refletem valores culturais e sociais.",
  "A teoria do empoderamento examina como grupos marginalizados buscam adquirir poder e controle sobre suas vidas.",
  "A sociologia da violência explora causas, padrões e impactos de comportamentos violentos na sociedade.",
  "A teoria da dependência destaca as relações de poder desiguais entre nações desenvolvidas e em desenvolvimento.",
  "A sociologia do consumo investiga padrões de compra, publicidade e o papel do consumo na identidade social.",
  "A teoria do habitus, proposta por Pierre Bourdieu, destaca como as disposições internalizadas influenciam comportamentos e escolhas.",
  "A sociologia da sexualidade estuda as normas, práticas e identidades sexuais em diferentes culturas e sociedades.",
  "A teoria do discurso, na sociologia da linguagem, explora como o discurso molda e é moldado por estruturas sociais.",
  "A sociologia do riso examina como o humor reflete e influencia as dinâmicas sociais.",
  "A teoria da modernidade reflexiva destaca a reflexividade nas sociedades contemporâneas, onde as pessoas refletem sobre suas próprias ações.",
  "A sociologia da educação física investiga o papel do esporte e atividade física nas instituições educacionais.",
  "A teoria do contato, na sociologia intergrupal, explora como interações positivas entre grupos podem reduzir preconceitos.",
  "A sociologia da emoção estuda como as emoções são socialmente construídas e expressas.",
  "A teoria do ciclo de vida familiar destaca as mudanças na estrutura familiar ao longo das diferentes fases da vida.",
  "A sociologia da comunicação examina como as interações comunicativas moldam as relações sociais e a cultura.",
  "A teoria da ação coletiva explora como os indivíduos agem em conjunto para alcançar objetivos compartilhados.",
  "A sociologia da alimentação investiga padrões alimentares, cultura alimentar e o papel da alimentação na identidade social.",
  "A teoria da modernização propõe que as sociedades passam por estágios previsíveis de desenvolvimento em direção à modernidade.",
  "A sociologia da religião explora como as crenças religiosas influenciam as estruturas sociais e a cultura.",
  "A teoria da dominação e resistência destaca como os grupos marginalizados resistem à opressão em sociedades hierárquicas.",
  "A sociologia da cidade analisa o desenvolvimento urbano, comunidades urbanas e impactos sociais da vida na cidade.",
  "A teoria do construtivismo social destaca como a realidade social é construída através da interação e interpretação coletiva.",
  "A sociologia do envelhecimento examina questões relacionadas ao envelhecimento da população, cuidados aos idosos e estereótipos associados à velhice.",
  "A teoria da socialização explora como os indivíduos aprendem normas e valores sociais ao longo de suas vidas.",
  "A sociologia da religião estuda as interações entre as crenças religiosas e as estruturas sociais.",
  "A teoria do feminismo marxista destaca as interseções entre gênero, classe e raça na análise da opressão.",
  "A sociologia da cidade analisa o desenvolvimento urbano, comunidades urbanas e impactos sociais da vida na cidade.",
  "A teoria da modernização propõe que as sociedades passam por estágios previsíveis de desenvolvimento em direção à modernidade.",
  "A sociologia do trabalho explora as relações entre trabalho, emprego e estrutura social.",
  "A teoria do conflito de gênero destaca as desigualdades sociais baseadas no gênero e os sistemas patriarcais.",
      ];
    const curiositiesArqueologia = [
      
      "A arqueologia é a disciplina que estuda vestígios materiais da atividade humana no passado, como artefatos, estruturas e restos humanos.",
  "A descoberta da tumba do faraó Tutancâmon, por Howard Carter em 1922, foi um dos achados arqueológicos mais significativos do século XX.",
  "A datação por radiocarbono é uma técnica comumente usada para determinar a idade de materiais orgânicos antigos, baseada na taxa de decaimento do carbono-14.",
  "A cidade perdida de Machu Picchu, redescoberta por Hiram Bingham em 1911, é uma das maravilhas arqueológicas dos Andes.",
  "O sítio arqueológico de Pompeia, enterrado pela erupção do Monte Vesúvio em 79 d.C., proporcionou uma visão única da vida romana antiga.",
  "A arqueologia subaquática explora sítios afundados, como naufrágios, revelando informações sobre comércio marítimo e culturas costeiras.",
  "A descoberta da antiga cidade suméria de Ur, por Leonard Woolley na década de 1920, trouxe à luz a civilização mesopotâmica.",
  "A técnica de LiDAR é usada na arqueologia para mapear o terreno e identificar características arqueológicas abaixo da vegetação.",
  "O Códice Maia de Dresden é um manuscrito maia que contém informações sobre astronomia, matemática e rituais religiosos.",
  "A arqueologia experimental envolve recriar condições históricas para entender o funcionamento de ferramentas, técnicas e construções antigas.",
  "O sítio de Göbekli Tepe, na Turquia, é um complexo arqueológico com pilares de pedra esculpidos, sugerindo atividades ritualísticas pré-históricas.",
  "O navio viking de Oseberg, descoberto na Noruega, é famoso por suas esculturas intrincadas e bem preservadas.",
  "A descoberta da antiga cidade de Troia, por Heinrich Schliemann em 1870, contribuiu para validar a existência do épico de Homero, a Ilíada.",
  "A Grande Pirâmide de Gizé, construída durante a Quarta Dinastia do Antigo Egito, é uma das Sete Maravilhas do Mundo Antigo.",
  "O estudo de microfósseis, como pólen e esporos, permite aos arqueólogos reconstruir ambientes antigos e padrões de ocupação humana.",
  "A Caverna de Altamira, na Espanha, contém pinturas rupestres paleolíticas notáveis, representando animais e cenas de caça.",
  "A descoberta do sítio de Stonehenge, na Inglaterra, revelou um complexo neolítico associado a práticas rituais e astronômicas.",
  "A análise de isótopos estáveis em ossos antigos ajuda a rastrear padrões de dieta e mobilidade de populações antigas.",
  "Os geoglifos de Nasca, no Peru, são enormes desenhos no solo, alguns com vários quilômetros de extensão, criados pela remoção de pedras para revelar o solo mais claro.",
  "A tumba de Qin Shi Huang, o primeiro imperador da China, contém o famoso Exército de Terracota, com milhares de soldados e cavalos esculpidos em argila.",
  "O Método Harris, uma técnica de escavação estratigráfica, é amplamente utilizado na arqueologia para entender a sequência temporal de camadas de solo.",
  "A roseta de Roseta, encontrada no Egito, foi crucial para decifrar os hieróglifos egípcios, fornecendo a chave para a tradução.",
  "A arqueologia forense aplica técnicas arqueológicas na resolução de crimes, incluindo a busca por evidências em locais de sepultamento clandestino.",
  "O sítio de Çatalhöyük, na Turquia, é uma antiga cidade neolítica com casas construídas lado a lado, sem ruas visíveis.",
  "A descoberta da cidade de Mohenjo-daro, no Vale do Indo, revelou uma sofisticada civilização urbana com sistemas de drenagem e escrita.",
  "A arqueologia histórica estuda períodos mais recentes, usando documentos escritos, mapas e evidências materiais para reconstruir o passado.",
  "A técnica de datação por termoluminescência é usada para determinar a data da última exposição de materiais cerâmicos à luz ou calor.",
  "Os petroglifos, gravuras em rochas, são encontrados em várias partes do mundo e muitas vezes representam símbolos religiosos, cenas de caça e rituais.",
  "O sítio de Catal Huyuk, na Turquia, é uma das primeiras comunidades urbanas conhecidas, datando do período Neolítico.",
  "A arqueologia urbana estuda restos arqueológicos em ambientes urbanos modernos, revelando camadas históricas abaixo da superfície da cidade.",
  "O tesouro de Sutton Hoo, no Reino Unido, inclui um impressionante capacete e outros objetos enterrados em um navio funerário anglo-saxão.",
  ];
    const curiositiesCriminologia = [
      "A criminologia é o estudo científico do crime, comportamento criminoso, vítimas e controle social.",
  "Cesare Lombroso, considerado o pai da criminologia, propôs teorias sobre a relação entre características físicas e predisposição para o crime.",
  "A teoria da rotulação (labeling theory) destaca como as etiquetas sociais influenciam o comportamento criminoso e a identidade do criminoso.",
  "O teste de polígrafo (detector de mentiras) é usado em investigações criminais, embora sua precisão e confiabilidade sejam controversas.",
  "A criminologia ambiental explora como o ambiente físico e social pode influenciar as taxas de criminalidade em determinadas áreas.",
  "A teoria da subcultura delinquente sugere que certos grupos sociais desenvolvem valores e normas que favorecem o comportamento criminoso.",
  "A criminologia feminista critica abordagens tradicionais, destacando a necessidade de considerar gênero e feminismo nas análises criminais.",
  "O criminoso em série Ted Bundy era conhecido por sua aparência carismática, o que desafiou estereótipos sobre como os assassinos em série parecem.",
  "A Lei de Três Greves, em alguns sistemas jurídicos, impõe penas mais severas a indivíduos condenados por crimes graves após terem cumprido duas penas anteriores.",
  "O crime organizado envolve atividades criminosas coordenadas por grupos estruturados, como máfias e cartéis.",
  "O Banco de Dados Nacional de Impressões Digitais (NDDB) nos Estados Unidos é uma ferramenta crucial na resolução de crimes através da identificação de suspeitos.",
  "A teoria do controle social destaca a importância das conexões sociais e relações familiares na prevenção do comportamento criminoso.",
  "A vitimologia estuda o papel da vítima no crime, incluindo como fatores individuais podem aumentar a vulnerabilidade.",
  "O conceito de 'crimes de colarinho branco' foi cunhado por Edwin Sutherland para descrever delitos cometidos por pessoas de status social elevado no contexto de seus empregos.",
  "A criminologia biossocial explora a interação entre fatores genéticos e ambientais na predisposição para o comportamento criminoso.",
  "O Modelo de Análise Ambiental (MAE) é usado para avaliar riscos e vulnerabilidades em uma área específica em relação à criminalidade.",
  "A criminologia crítica examina as estruturas sociais que contribuem para o crime e questiona o papel das instituições na criação de desigualdades.",
  "O criminoso Al Capone, um dos gangsters mais famosos da história, foi condenado por evasão fiscal, não por suas atividades criminosas mais notórias.",
  "A pena de morte, embora ainda seja aplicada em alguns lugares, é amplamente debatida devido a questões éticas e possíveis erros judiciais.",
  "A criminologia é uma disciplina interdisciplinar, incorporando elementos da sociologia, psicologia, ciência forense e direito.",
   "A teoria do rótulo social destaca como a sociedade rotula certos comportamentos como criminosos, afetando a identidade do indivíduo rotulado.",
  "A criminologia é fundamental para o sistema de justiça criminal, ajudando a entender padrões criminais, motivos e prevenção.",
  "O crime de colarinho branco pode envolver fraudes financeiras, corrupção corporativa e outras atividades ilegais relacionadas a negócios.",
  "O estudo da 'Zona de Desconforto' explora como fatores ambientais desconfortáveis podem influenciar comportamentos antissociais.",
  "A teoria do controle diferencial argumenta que as pessoas pesam os custos e benefícios antes de decidirem cometer um crime.",
  "O método de Identificação por Impressões Digitais foi pioneiramente introduzido por Sir Francis Galton no final do século XIX.",
  "A criminologia verde foca em crimes ambientais, incluindo poluição, desmatamento ilegal e tráfico de animais.",
  "A vitimologia de estilo de vida estuda como o estilo de vida de uma pessoa pode aumentar ou diminuir sua probabilidade de ser vítima de crime.",
  "A 'Escola de Chicago' foi pioneira na aplicação de teorias sociológicas para entender padrões criminais em áreas urbanas.",
  "O Teste de Personalidade Psicopática (PCL-R) é frequentemente usado para avaliar a psicopatia em indivíduos, incluindo criminosos.",
  "A teoria da anomia, desenvolvida por Émile Durkheim, sugere que o crime pode ocorrer quando as normas sociais são enfraquecidas.",
  "O Código de Hammurabi, uma das primeiras codificações legais conhecidas, datado de cerca de 1754 a.C., incluía punições para crimes específicos.",
  "O conceito de justiça restaurativa enfatiza a reparação do dano causado pela criminalidade, envolvendo tanto vítimas quanto infratores.",
  "A teoria do controle social sugere que os laços sociais e o apoio comunitário são fundamentais para prevenir comportamentos criminosos.",
  "A análise de perfis criminais, popularizada pelo FBI, envolve a identificação de características psicológicas de criminosos com base em padrões de crime.",
  "O Criminogenic Effect é um conceito que destaca como certas condições podem aumentar a probabilidade de comportamento criminoso.",
  "A criminologia feminista critica a tradicional marginalização de mulheres nos estudos criminais, buscando uma perspectiva mais inclusiva.",
  "A pena de prisão perpétua é uma alternativa à pena de morte em alguns sistemas jurídicos, mantendo o criminoso na prisão pelo resto da vida.",
  "O Movimento da Reforma Penal do século XIX buscou humanizar o sistema penitenciário, enfocando reabilitação em vez de punição.",
  "A criminologia pós-moderna critica as narrativas 'grandes' e busca entender a multiplicidade de perspectivas no estudo do crime.",
  "O termo 'crimigração' refere-se à interseção entre políticas de imigração e questões criminais, destacando a criminalização de imigrantes.",
  "A teoria do rótulo social destaca como ser rotulado como criminoso pode levar à autoperpetuação do comportamento criminoso.",
  "O 'Efeito CSI' refere-se à influência da representação de investigações criminais em programas de televisão na percepção pública do sistema judicial.",
  "A teoria da escolha racional sugere que os criminosos pesam os custos e benefícios antes de cometerem um crime, agindo de forma racional.",
  "O 'efeito espetáculo' ocorre quando crimes e julgamentos são amplamente cobertos pela mídia, afetando a percepção pública e o sistema judicial.",
  "A criminologia cultural examina como os elementos culturais e subculturais podem influenciar a criminalidade e as respostas sociais.",
  "A Lei RICO (Racketeer Influenced and Corrupt Organizations Act) nos EUA visa combater organizações criminosas por meio de acusações financeiras.",
  "A teoria do controle social de Hirschi argumenta que os laços sociais, comprometimento, envolvimento, crença e afeto, são cruciais para prevenir o crime.",
  "A violência simbólica, conforme explorada pela criminologia crítica, destaca como certas estruturas sociais perpetuam a violência de maneiras sutis.",
  "O 'Efeito de Novidade' pode influenciar a percepção do risco criminoso, destacando a importância da atenção da mídia em certos eventos.",
  "A análise situacional é uma abordagem criminológica que se concentra em circunstâncias específicas de um crime para informar estratégias de prevenção.",
  "O conceito de 'crimes sem vítimas' refere-se a comportamentos que violam a lei, mas não causam danos diretos a outra pessoa.",
  "A teoria do conflito destaca como o conflito social e a desigualdade podem levar a comportamentos criminosos como uma forma de protesto ou resistência.",
  "A vitimologia radical explora como as estruturas sociais, incluindo o patriarcado e o racismo, contribuem para a vitimização.",
  "A criminologia positivista busca entender cientificamente os fatores que contribuem para o comportamento criminoso, incluindo influências biológicas e psicológicas.",
  "O conceito de 'bairros desorganizados' destaca como a falta de coesão social pode contribuir para taxas mais altas de criminalidade em determinadas áreas.",
  "O termo 'criminologia global' refere-se ao estudo da criminalidade em escala global, considerando fatores como globalização, migração e comércio ilegal.",
  "O Princípio da Proporcionalidade, aplicado no sistema legal, destaca a importância de que a punição seja proporcional à gravidade do crime.",
  "A teoria do labelling sugere que rotular alguém como criminoso pode resultar na internalização dessa identidade, influenciando comportamentos futuros."
      ];



    const curiositiesCulturaPop = [
        "A expressão 'cultura pop' refere-se à cultura popular, abrangendo elementos como música, cinema, moda, televisão, quadrinhos e muito mais.",
  "O termo 'cultura pop' ganhou destaque na década de 1950, mas suas raízes remontam à ascensão da cultura de massa no século XIX.",
  "Os Beatles, uma das bandas mais icônicas da história da música pop, têm mais de um bilhão de singles vendidos.",
  "O primeiro filme a usar a palavra 'nerd' foi 'A Vingança dos Nerds', lançado em 1984, contribuindo para popularizar o termo.",
  "O Super Mario, ícone dos videogames, foi criado por Shigeru Miyamoto e fez sua estreia em 1985 no jogo 'Super Mario Bros'.",
  "O Festival de Woodstock, realizado em 1969, é um marco na cultura pop, simbolizando a contracultura e a música da época.",
  "Os Simpsons, uma série de animação que estreou em 1989, é a série de maior duração na história da televisão norte-americana.",
  "A cultura pop influencia a moda de maneira significativa, com artistas e personagens populares muitas vezes ditando tendências.",
  "Michael Jackson, conhecido como o 'Rei do Pop', é um dos artistas musicais mais vendidos e influentes da história.",
  "A franquia Star Wars, criada por George Lucas, começou em 1977 e se tornou uma das sagas cinematográficas mais populares e influentes.",
  "Os quadrinhos da Marvel e DC, com personagens como Homem-Aranha e Batman, desempenham um papel fundamental na cultura pop e inspiraram inúmeras adaptações.",
  "A popularidade dos memes na internet é um fenômeno da cultura pop contemporânea, refletindo o humor e a comunicação online.",
  "O termo 'fanboy' ou 'fangirl' é usado para descrever entusiastas excessivamente dedicados a uma determinada franquia ou artista da cultura pop.",
  "O videogame Pac-Man, lançado em 1980, é um dos jogos mais reconhecíveis e bem-sucedidos da história dos arcades.",
  "O movimento cosplay, em que as pessoas se vestem como seus personagens favoritos da cultura pop, tornou-se uma parte integrante de eventos geek e convenções.",
  "O primeiro filme em 3D foi 'O Homem da Máscara de Ferro', lançado em 1953, marcando um avanço tecnológico na indústria cinematográfica.",
  "O termo 'geek' evoluiu de uma conotação negativa para representar orgulhosamente entusiastas de tecnologia, ficção científica e cultura pop.",
  "O álbum 'Thriller' de Michael Jackson, lançado em 1982, é o álbum mais vendido de todos os tempos.",
  "A série de livros 'Harry Potter', escrita por J.K. Rowling, tornou-se um fenômeno global, impactando tanto a literatura quanto o cinema.",
  "Os emojis, agora uma parte integrante da comunicação online, surgiram nos anos 1990 e são derivados da cultura pop japonesa.",
  "O icônico logotipo da Coca-Cola foi criado em 1886 e se tornou um dos símbolos mais reconhecidos na cultura pop.",
  "O videoclipe de 'Thriller' de Michael Jackson, lançado em 1983, é considerado um dos vídeos musicais mais influentes da história.",
  "Os Beatles são os únicos artistas a terem simultaneamente as cinco principais músicas nos EUA.",
  "Os emojis foram adicionados ao Unicode em 2010, facilitando sua inclusão em mensagens digitais em todo o mundo.",
  "A cultura pop influencia o design de produtos, desde roupas e acessórios até eletrônicos e itens de decoração.",
  "O movimento punk, surgido nos anos 70, teve um impacto significativo na música e na moda da cultura pop.",
  "O primeiro videoclipe da MTV foi 'Video Killed the Radio Star' da banda The Buggles, lançado em 1981.",
  "O criador do Facebook, Mark Zuckerberg, é conhecido por ser fã da série de ficção científica 'Star Trek'.",
  "A palavra 'meme' foi cunhada por Richard Dawkins em seu livro 'O Gene Egoísta', mas ganhou novo significado na cultura pop online.",
  "O termo 'jump the shark' originou-se de um episódio de 'Happy Days', indicando o declínio de uma série de TV.",
  "O videogame Pong, lançado em 1972, é frequentemente considerado o primeiro videogame comercialmente bem-sucedido.",
  "O fenômeno de séries 'binge-watch' tornou-se popular com o advento de serviços de streaming como Netflix.",
  "A série de desenhos animados 'Os Flintstones', estreando em 1960, foi a primeira série animada a ser exibida durante o horário nobre.",
  "O termo 'fan service' refere-se a elementos adicionados a uma obra para agradar aos fãs, muitas vezes na forma de referências ou momentos emocionantes.",
  "O filme 'Matrix', lançado em 1999, impactou significativamente a cultura pop, especialmente no que diz respeito à ficção científica e efeitos visuais.",
  "O primeiro videoclipe a ser exibido na MTV Europe foi 'Money for Nothing' da banda Dire Straits.",
  "O personagem Mario da Nintendo apareceu pela primeira vez em 1981 no jogo 'Donkey Kong'.",
  "O Batman é um dos personagens de quadrinhos mais adaptados, aparecendo em várias séries de TV, filmes e jogos.",
  "A série de TV 'Friends' permanece popular mesmo após seu término em 2004, continuando a conquistar novas gerações de fãs.",
  "O emoji mais usado globalmente em 2021 foi o rosto sorridente com lágrimas de alegria.",
  "A série 'Game of Thrones' é baseada na série de livros 'As Crônicas de Gelo e Fogo' de George R.R. Martin.",
  "O emoji de coração vermelho é amplamente utilizado como símbolo de amor e carinho nas redes sociais.",
  "O álbum 'The Dark Side of the Moon' da banda Pink Floyd é famoso por permanecer 741 semanas consecutivas nas paradas da Billboard.",
  "O termo 'mashup' refere-se à combinação de elementos de diferentes músicas para criar uma nova peça musical.",
  "O jogo de tabuleiro 'Monopoly' foi criado nos anos 1930 e continua sendo um dos jogos mais populares do mundo.",
  "O designer de moda Karl Lagerfeld era conhecido por seu amor por gatos e tinha uma gata chamada Choupette.",
  "O meme 'Distracted Boyfriend' tornou-se viral na internet, sendo usado para representar infidelidade e distração.",
  "A franquia Pokémon, criada por Satoshi Tajiri, inclui jogos, desenhos animados, filmes e uma grande variedade de produtos.",
  "O termo 'shipping' na cultura pop refere-se ao apoio ou desejo de que dois personagens fictícios formem um relacionamento.",
  "A música 'Gangnam Style' de PSY se tornou um fenômeno global e é o primeiro vídeo do YouTube a atingir 1 bilhão de visualizações.",
  "Os filmes da Marvel têm uma prática de incluir cenas pós-créditos, muitas vezes revelando pistas sobre futuras produções.",
  "O Festival de Cinema de Cannes, realizado na França, é um dos eventos cinematográficos mais prestigiados do mundo.",
  "O romance 'Orgulho e Preconceito', de Jane Austen, influenciou inúmeras adaptações cinematográficas e séries de TV.",
  "O videoclipe de 'Gangnam Style' quebrou o contador de visualizações do YouTube, levando à atualização da plataforma.",
  "O autor de ficção científica Philip K. Dick teve várias de suas obras adaptadas para o cinema, incluindo 'Blade Runner' e 'Minority Report'.",
  "A série 'Stranger Things' homenageia e faz referências a várias obras dos anos 80, desde filmes a jogos de tabuleiro.",
  "O emoji de palmas é comumente usado online para expressar aprovação ou reconhecimento.",
  "O videogame 'Tetris' foi criado por Alexey Pajitnov e tornou-se um dos jogos mais vendidos de todos os tempos.",
  "A série 'The Twilight Zone', criada por Rod Serling, é conhecida por suas histórias de ficção científica e reviravoltas surpreendentes.",
  "O termo 'nerdvana' é usado para descrever um estado de grande felicidade alcançado por meio de interesses nerds, como filmes, jogos e quadrinhos."
  
  ];
  
  
  
  
    const curiositiesCulturaGotica = [
      "A cultura gótica, originada nos anos 80, é um movimento subcultural que se estende além da música para influenciar moda, arte e estilo de vida.",
  "O movimento arquitetônico gótico medieval, caracterizado por arcos pontiagudos e vitrais, inspirou a estética da cultura gótica.",
  "O Dia das Bruxas (Halloween) tem ligações com a cultura gótica, compartilhando elementos macabros e uma apreciação pela estética sombria.",
  "O romance gótico, surgido no século XVIII com obras como 'O Castelo de Otranto', de Horace Walpole, é um subgênero literário associado à cultura gótica.",
  "A música gótica abrange diversos estilos, incluindo deathrock, darkwave e post-punk, e é marcada por letras introspectivas e atmosferas melancólicas.",
  "Bauhaus, Siouxsie and the Banshees e The Cure são bandas-chave que moldaram a cena musical gótica, cada uma contribuindo com uma abordagem única.",
  "O estilo de moda gótica incorpora peças escuras, couro, rendas e acessórios distintos, refletindo uma expressão individual e autêntica.",
  "A estética gótica nas artes visuais valoriza elementos macabros, como esqueletos, corvos e símbolos associados à morte, explorando a beleza na escuridão.",
  "Festivais góticos, como o Wave-Gotik-Treffen, reúnem entusiastas globalmente, proporcionando uma celebração da diversidade dentro da comunidade gótica.",
  "O romantismo sombrio é uma característica proeminente na literatura e na arte gótica, explorando temas de melancolia, amor e a transitoriedade da vida.",
  "O Vampirismo é um tema recorrente, influenciando obras literárias como 'Drácula', de Bram Stoker, e contribuindo para a mitologia gótica.",
  "A cultura gótica é caracterizada pela rejeição de estereótipos, incentivando a autenticidade e a valorização da individualidade dentro da comunidade.",
  "O símbolo da cruz invertida, associado à estética gótica, muitas vezes representa uma inversão de valores tradicionais e uma crítica à normatividade.",
  "A série de quadrinhos 'The Sandman', de Neil Gaiman, explora elementos góticos e mitológicos, incorporando narrativas complexas e personagens cativantes.",
  "O filme 'O Corvo' (The Crow), baseado na história em quadrinhos de James O'Barr, tornou-se um ícone gótico do cinema, destacando elementos de tragédia e redenção.",
  "O minimalismo na moda gótica, conhecido como 'bats and crosses', simplifica a estética, destacando símbolos como morcegos e cruzes.",
  "A cultura gótica, globalmente difundida, manifesta-se em diversas formas de arte e mídia, influenciando subculturas contemporâneas em todo o mundo.",
  "O movimento gótico é caracterizado por uma apreciação pela estética sombria, o sublime e uma sensibilidade artística única.",
  "A poesia gótica, muitas vezes expressando emoções intensas, explora temas como amor proibido, desespero e a efemeridade da vida.",
  "A comunidade gótica online é ativa em plataformas como Tumblr, Instagram e Reddit, proporcionando um espaço para compartilhamento de arte, ideias e apoio mútuo.",
  "A influência da cultura gótica transcende suas origens, sendo visível em diversas subculturas contemporâneas que incorporam elementos de sua estética e atitude.",
  "A cultura gótica abraça a nostalgia, muitas vezes apreciando elementos do passado, como a era vitoriana e a literatura gótica clássica.",
  "A expressão artística na cultura gótica muitas vezes explora temas existenciais, ocultismo, simbolismo e uma profunda conexão com a natureza.",
  "A cultura gótica tem uma relação complexa com a religião, muitas vezes desafiando normas religiosas enquanto incorpora simbolismos religiosos em sua estética.",
  "O termo 'gótico' originalmente referia-se a tribos germânicas, e seu uso para descrever a subcultura gótica começou como uma ironia, mas foi adotado pelos próprios adeptos.",
  "O gótico é muitas vezes visto como uma subcultura intelectual, valorizando a literatura, a arte e a música de maneira aprofundada e crítica.",
  "A cultura gótica tem conexões com o movimento romântico, compartilhando uma apreciação pela individualidade e uma fascinação pelo sublime.",
  "As convenções e festivais góticos são oportunidades para a comunidade compartilhar interesses, exibir criações artísticas e fortalecer laços sociais.",
  "A estética gótica pode ser encontrada em várias formas de entretenimento, incluindo videogames, onde influencia ambientes, enredos e personagens.",
  "A cultura gótica possui uma forte comunidade online, com blogs, fóruns e grupos dedicados a compartilhar informações, arte e experiências.",
  "Muitos artistas contemporâneos incorporam elementos da cultura gótica em sua obra, contribuindo para sua presença contínua na cena artística.",
  "O minimalismo na moda gótica é muitas vezes uma declaração contra o consumismo, enfatizando qualidade sobre quantidade e a singularidade das peças.",
  "A literatura gótica moderna, como os trabalhos de Neil Gaiman e Anne Rice, continua a expandir os temas e elementos da cultura gótica.",
  "A subcultura gótica desafia padrões de gênero, encorajando a expressão pessoal e a quebra de estereótipos ligados à aparência e comportamento.",
  "A cultura gótica tem influência em estilos de dança, como o vogue, e expressões artísticas que desafiam as convenções do movimento do corpo.",
  "O gótico é muitas vezes associado a uma apreciação pela beleza na decadência, explorando a estética do envelhecimento e da transitoriedade.",
  "Os eventos góticos frequentemente apresentam feiras de arte e artesanato, incentivando a produção e a valorização de itens únicos e artesanais.",
  "O DIY (faça você mesmo) é um valor central na cultura gótica, encorajando a criação de roupas, acessórios e arte personalizados.",
  "O filme expressionista alemão 'Nosferatu' é um marco influente na cultura gótica cinematográfica, contribuindo para a representação estética dos vampiros.",
  "A cultura gótica é dinâmica e evolui constantemente, incorporando novas influências e mantendo uma abordagem crítica em relação ao mundo."
  
      ];
    
        
        
        

        const selectedCategory = categories[selectedCategoryIndex];
            const selectedCuriositiesArray = eval(`curiosities${selectedCategory.replace(/\s+/g, '')}`); // Dynamically get the array based on category

            if (selectedCuriositiesArray && selectedCuriositiesArray.length > 0) {
                const randomCuriosity = pickRandom(selectedCuriositiesArray);
                await m.reply(randomCuriosity);
    } 
}


/* catch (i) {
try {
const anime2 = `https://api.zahwazein.xyz/photoeditor/jadianime?url=${image}&apikey=${keysxxx}`;
await conn.sendFile(m.chat, anime2, 'error.jpg', null, m);
} catch (a) {
try {
const anime3 = `https://api.caliph.biz.id/api/animeai?img=${image}&apikey=caliphkey`;
await conn.sendFile(m.chat, anime3, 'error.jpg', null, m);
} catch (e) {
throw `${lenguajeGB.smsAvisoFG()}❖─┅──┅\n𝗘𝗥𝗥𝗢 💀
𝗩𝗘𝗥𝗜𝗙𝗜𝗤𝗨𝗘 𝗦𝗘 𝗛Á 𝗗𝗘 𝗙𝗔𝗧𝗢 𝗔 𝗙𝗔𝗖𝗘 𝗗𝗘 𝗔𝗟𝗚𝗨𝗠𝗔 𝗣𝗢𝗕𝗥𝗘 𝗔𝗟𝗠𝗔 𝗡𝗘𝗦𝗧𝗔 𝗙𝗢𝗧𝗢\n─┅──┅❖ `
}}} */
  
  
}}
handler.help = ['curiosidades'];
handler.tags = ['tools'];
export default handler;
handler.command = /^(curiosidades|curi|fatos)$/i;
